### PR TITLE
Rely on zc.lockfile for file locking behavior

### LINKED ISSUE #23: Add cross-platform support
UNIX assumption causes issue with Windows: this dist unconditionally imports `fcntl`, which crashes tests during setup time, when `pytest` looks up for and tries to import fixtures: https://ci.appveyor.com/project/CherryPy/cherrypy/build/1.0.444/job/seei217vtwplqk6h#L500

(Ref https://github.com/pytest-dev/pytest-services/issues/22#issuecomment-419751978)

### PR DESCRIPTION
**Pull request by jaraco**
This PR represents the preferred alternative to #24, relying on the new zc.lockfile 2.0 and fixes #23.

---
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-services/27)

### CODE REVIEW

**Comment by jaraco** [comment]
The tests are failing and I don't understand why. The error seems to be coming from mysql rejecting that the data dir is not empty. However, the `mysql_defaults_file` writes to the `mysql_data_dir` unconditionally, so I don't see how these tests wouldn't fail at master.

**Comment by jaraco** [comment]
I've restarted [this build](https://travis-ci.org/pytest-dev/pytest-services/jobs/477465558) to see if the tests are failing in master, but the test still passed.

**Comment by jaraco** [comment]
I don't know what else to try here. I'm unable to debug because I can't build locally. I've tried to `brew install mysql`, but that [has a bug](https://github.com/Homebrew/homebrew-core/issues/4534) that I've tried to workaround, but even then, after successfully building mysqlclient, the test suite fails when trying to compile pylibmc:

```
  Running setup.py install for pylibmc: started
    Running setup.py install for pylibmc: finished with status 'error'
    Complete output from command /Users/jaraco/code/public/pytest-services/.tox/py37/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-install-9auhr_rb/pylibmc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-record-domvzwzl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jaraco/code/public/pytest-services/.tox/py37/include/site/python3.7/pylibmc:
    /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-install-9auhr_rb/pylibmc/setup.py:98: DeprecationWarning: 'U' mode is deprecated
      with open("README.rst", "U", encoding="utf-8") as r:
    /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-install-9auhr_rb/pylibmc/setup.py:100: DeprecationWarning: 'U' mode is deprecated
      with open("src/pylibmc-version.h", "U", encoding="utf-8") as r:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/pylibmc
    copying src/pylibmc/autoconf.py -> build/lib.macosx-10.9-x86_64-3.7/pylibmc
    copying src/pylibmc/pools.py -> build/lib.macosx-10.9-x86_64-3.7/pylibmc
    copying src/pylibmc/client.py -> build/lib.macosx-10.9-x86_64-3.7/pylibmc
    copying src/pylibmc/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/pylibmc
    copying src/pylibmc/test.py -> build/lib.macosx-10.9-x86_64-3.7/pylibmc
    copying src/pylibmc/consts.py -> build/lib.macosx-10.9-x86_64-3.7/pylibmc
    copying src/pylibmc/__main__.py -> build/lib.macosx-10.9-x86_64-3.7/pylibmc
    running build_ext
    building '_pylibmc' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/usr/local/opt/openssl/include -DUSE_ZLIB -I/Users/jaraco/code/public/pytest-services/.tox/py37/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/_pylibmcmodule.c -o build/temp.macosx-10.9-x86_64-3.7/src/_pylibmcmodule.o -fno-strict-aliasing -std=c99
    In file included from src/_pylibmcmodule.c:34:
    src/_pylibmcmodule.h:42:10: fatal error: 'libmemcached/memcached.h' file not found
    #include <libmemcached/memcached.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by jaraco** [comment]
Even after installing `libmemcached` using `brew install`, the tests continue to fail with other issues like:

```
tests/test_plugin.py::test_mysql
  /Users/jaraco/code/public/pytest-services/.tox/python/lib/python3.8/site-packages/pytest_services/mysql.py:51: PytestAssertRewriteWarning: asserting the value None, please use "assert is None"
    assert mysql_install_db, 'You have to install mysql_install_db script.'
```

It seems there are issues with `mysql_install_db` not existing. I think I saw some deprecation warnings about that command.

**Comment by bubenkoff** [comment]
that script depends on the installed mysql version of course
most recent from brew is the latest so this needs to be updated as well

**Comment by jaraco** [comment]
On further examination, the issue does appear to be present in master, as reported in #29. I'm not sure why re-running a previous test didn't capture the failure, but just re-tagging the master to master-redux caused the tests to run again and fail this time with the same failure that's blocking acceptance of this issue. I suspect once #29 is fixed, this proposal will also pass tests.

**Comment by jaraco** [comment]
This latest branch is rebased on #31.

**Comment by jaraco** [comment]
I need to do more work on this issue before #23 is fully addressed.

**Comment by jaraco** [comment]
Okay. I've done some more work on this. I've updated the changelog. I've also removed the unused import of fcntl. I suspect this change will help solve #23, but probably still doesn't add full cross-platform support. In fact, I'm aware of two issues:

- [ ] Xvfb tests fail on macOS when xvfb isn't available.
- [ ] tests fail to run on Windows because pylibmc doesn't install.

Still, I think these changes should be accepted and released.

I've tested the branch and confirmed that on windows, one can now `import pytest_services.mysql, pytest_services.xvfb` after pip install pytest-services.

**Comment by bubenkoff** [comment]
@jaraco 
thanks, please merge and make a new release (please give your pypi username and i'll add you)

**Comment by jaraco** [comment]
@bubenkoff My PyPI username is [jaraco](https://pypi.org/user/jaraco). Happy to cut a release.

**Comment by bubenkoff** [comment]
thanks, done

**Pull request merged**
