### PR TITLE
"slave" -> "worker" for xdist compat

### LINKED ISSUE #34: Upcoming incompatibility in pytest-xdist 2.0: "slave" aliases removed
Hi!

As per https://github.com/pytest-dev/pytest-xdist/pull/541, pytest-xdist 2.0 will remove the deprecated "slave" 
aliases, which have been replaced by "worker" since pytest-xdist 1.22.

To avoid breakage, the team suggests to update your package to use the new terms, and make a new release to avoid sudden breakages once pytest-xdist 2.0 is released.

cc @Zac-HD @RonnyPfannschmidt

Thanks!

### PR DESCRIPTION
**Pull request by Zac-HD**
Closes #34.

---
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-services/35)

### CODE REVIEW

**Comment by Zac-HD** [comment]
@RonnyPfannschmidt done :slightly_smiling_face:

**Comment by Zac-HD** [comment]
@jaraco - if this looks good to you, could you cut a new release?

**Comment by jaraco** [comment]
What kind of version bump does this change require?

**Comment by jaraco** [comment]
Nevermind; I see it in the changelog. Released 8798e03 as 2.1.0.

**Pull request merged**
